spring:
  profiles:
    active: alpha
  redis:
    host: localhost
    port: 6379

  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: testKeySpace
      local-datacenter: DC1

